### ISSUE TITLE
[BUG] Can't build clightd-git r276.e8209e3-1

### ISSUE THREAD

**Issue by ro6** [FedeDP/Clight#103]
**Clight version the issue has been seen with:**
> `clightd-git r276.e8209e3-1`

**Used distribution:**
> `5.3.5-arch1-1-ARCH`

**Describe the bug**
```
==> Making package: clightd-git r276.e8209e3-1 (Sun 27 Oct 2019 09:26:20 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
-- The C compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
-- Checking for modules 'libudev;libmodule>=5.0.0'
--   Package dependency requirement 'libmodule >= 5.0.0' could not be satisfied.
Package 'libmodule' has version '4.2.0', required version is '>= 5.0.0'
CMake Error at /usr/share/cmake-3.15/Modules/FindPkgConfig.cmake:458 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.15/Modules/FindPkgConfig.cmake:637 (_pkg_check_modules_internal)
  CMakeLists.txt:27 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
See also "/home/ro6/.cache/yay/clightd-git/src/Clightd/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
    Aborting...
Error making: clightd-git
```

Is the intention that `clight-git` users build your `libmodule` library ahead of what's in the AUR? I'd rather be on the stable version, but I'm trying to get around #54 

Thanks!

**Comment by FedeDP** [comment]
Yes, both Clight and Clightd now needs libmodule 5.0.0, that is released but it is not available in AUR.
I did not yet push libmodule 5.0.0 to aur to avoid breaking stable clight and clightd installations (not -git ones).
I think that users using devel versions should expect some weird breakages sometimes (hopefully, very rarely) :) Thus, i preferred to break devel versions instead.
You should use l[ibmodule pkgbuild](https://github.com/FedeDP/libmodule/blob/master/Extra/Arch/PKGBUILD) provived by its git repo to install 5.0.0!
