### ISSUE TITLE
[BUG]  clight error while loading shared libraries

### ISSUE THREAD

**Issue by RezaSh13** [FedeDP/Clight#108]
systemctl status tor 

● clightd.service - Bus service to manage various screen related properties (gamma, dpms, backlight)
   Loaded: loaded (/usr/lib/systemd/system/clightd.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-12-10 01:28:02 +0330; 875ms ago
  Process: 13894 ExecStart=/usr/lib/clightd/clightd (code=exited, status=127)
 Main PID: 13894 (code=exited, status=127)

Dec 10 01:28:02 plasma systemd[1]: Starting Bus service to manage various screen related properties (gamma, dpms, backlight)...
Dec 10 01:28:02 plasma systemd[1]: clightd.service: Main process exited, code=exited, status=127/n/a
Dec 10 01:28:02 plasma clightd[13894]: /usr/lib/clightd/clightd: error while loading shared libraries: libddcutil.so.1: cannot open shared object file: No such file or directory
Dec 10 01:28:02 plasma systemd[1]: clightd.service: Failed with result 'exit-code'.
Dec 10 01:28:02 plasma systemd[1]: Failed to start Bus service to manage various screen related properties (gamma, dpms, backlight).

 plasma  ~  1 :( clight 
Clightd service could not be introspected. Automatic modules detection won't work.
No clightd found. Clightd is a mandatory dep.

 plasma  ~  clight --verbose
check_clightd_features(): Failed to activate service 'org.clightd.clightd': timed out (service_start_timeout=25000ms)
Clightd service could not be introspected. Automatic modules detection won't work.
check_clightd_version(): Failed to activate service 'org.clightd.clightd': timed out (service_start_timeout=25000ms)
No clightd found. Clightd is a mandatory dep.

I have manjaro

**Comment by FedeDP** [comment]
Hi!
You need to rebuild Clightd as ddcutil soversion was recently bumped!
