### ISSUE TITLE
clight hangs on no network connection

### ISSUE THREAD

**Issue by runical** [FedeDP/Clight#11]
As said on the Arch boards, I found a way to test (a sock over the webcam, works great :P )

Anyway, when running clight without a network connection and no defined location, it hangs on I assume getting the location. You might want to check for a network connection and maybe define a backup location in the config.
[clight.txt](https://github.com/FedeDP/Clight/files/998508/clight.txt)

**Comment by FedeDP** [comment]
Yes, i am aware of this issue.
If you check TODO, that is on my todo list for next release(caching location).
It is gonna be fixed soon:)
Thanks for your report!

**Comment by FedeDP** [comment]
Fixed in  f4e278e!

**Comment by FedeDP** [comment]
EDIT: obviously if at first start ever of clight (ie when no cache file is present), clight is run without lat/lon (so, with geoclue enabled) and no internet connection, it will hang still. Sadly, that issue cannot be prevented.

**Comment by runical** [comment]
Ah, my bad. I completely missed the TODO! Thanks for fixing it!
