### ISSUE TITLE
[FEATURE REQ] Granular keyboard backlight control

### ISSUE THREAD

**Issue by bradbrad2x** [FedeDP/Clight#112]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. EG: I'm always frustrated when [...]

Sometimes my keyboard does not change the keyboard backlight when needed in my current day to day conditions.

**Describe the solution you'd like**

I want to be able to control when the keyboard backlight brightens and dims according to the ambient brightness. It would be similar to the backlight regression points already implemented.

**Comment by FedeDP** [comment]
While this is quite easy to implement, usually keyboards have much less granular backlight control and thus it would be useless to have such feature.

Can you paste here output of:
`busctl call org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight GetMaxBrightness`?

**Comment by bradbrad2x** [comment]
> While this is quite easy to implement, usually keyboards have much less granular backlight control and thus it would be useless to have such feature.

Although keyboards usually have much less granular control, it would be nice to set when the keyboard backlight should turn on/off. For example, a scenario could be if I only want it to turn on if its really dark (<20% ambient).

> Can you paste here output of:
> `busctl call org.freedesktop.UPower /org/freedesktop/UPower/KbdBacklight org.freedesktop.UPower.KbdBacklight GetMaxBrightness`?

`i 3`

**Comment by FedeDP** [comment]
> Although keyboards usually have much less granular control, it would be nice to set when the keyboard backlight should turn on/off. For example, a scenario could be if I only want it to turn on if its really dark (<20% ambient).

I see, seems a legit use case indeed! Thanks for your input :)

**Comment by FedeDP** [comment]
What would you think about a threshold instead? Ie: if ambient brightness drops below the threshold, keyboard backlight will be managed just like now (ie: with a backlight level of `1.0 - ambient_br`.
On levels above this threshold, keyboard will be set to lowest value (ie: switched off).
It is much simpler and yet effective; having a 10-points curve for keyboards (that often have 3 backlight levels) seems unnecessarily complicated to me!

**Comment by bradbrad2x** [comment]
> What would you think about a threshold instead? Ie: if ambient brightness drops below the threshold, keyboard backlight will be managed just like now (ie: with a backlight level of `1.0 - ambient_br`.
> On levels above this threshold, keyboard will be set to lowest value (ie: switched off).
> It is much simpler and yet effective; having a 10-points curve for keyboards (that often have 3 backlight levels) seems unnecessarily complicated to me!

Yeah that would also work

**Comment by FedeDP** [comment]
Sorry for disappearing for so long!
Anyway, I still think that a threshold is the way to go; it is very simple, with minimum complexity added and it still should do the trick.
I may wait for other user inputs on this topic!

**Comment by FedeDP** [comment]
I've made available a threshold config for keyboard backlight; let me know if it works fine for you! Thank you very much for your testing!
