### ISSUE TITLE
[BUG]  clight 4.0-1 doesn't compile

### ISSUE THREAD

**Issue by simony2222** [FedeDP/Clight#130]
**Clight version the issue has been seen with:**
> clight 4.0-1

**Used distribution:**
> Arch Linux x86_64 (5.6.14-arch1-1)

**Describe the bug**
Clight doesn't compile (actualy I think it's Clightd, but both of them seemed liked). I will note that I have libmodule 5.0.0-1 installed, so my issue seems to be new compare to [this one](https://github.com/FedeDP/Clight/issues/103) for instance.

**Expected behavior**
For the Package to compile. ^^'

**To Reproduce**
Both pacmac and `yay -S clight` yielded the same result.

**Log**
Here is the full log and my inputs to reproduce what happened

`% yay -S clight 
:: There are 2 providers available for clight:
:: Repository AUR
    1) clight 2) clight-git 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 2]  clightd-4.0-2  clight-4.0-1

  2 clightd                                  (Build Files Exist)
  1 clight                                   (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> a
:: Deleting (1/2): /home/simon/.cache/yay/clightd
:: Deleting (2/2): /home/simon/.cache/yay/clight
:: Downloaded PKGBUILD (1/2): clightd
:: Downloaded PKGBUILD (2/2): clight
  2 clightd                                  (Build Files Exist)
  1 clight                                   (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> n
:: Parsing SRCINFO (1/2): clightd
:: Parsing SRCINFO (2/2): clight
==> Making package: clightd 4.0-2 (Fri 22 May 2020 10:15:33 PM UTC)
==> Retrieving sources...
  -> Downloading Clightd-4.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    428      0 --:--:-- --:--:-- --:--:--   429
100 36228    0 36228    0     0  34048      0 --:--:--  0:00:01 --:--:--  162k
==> Validating source files with sha256sums...
    Clightd-4.0.tar.gz ... Passed
==> Making package: clight 4.0-1 (Fri 22 May 2020 10:15:35 PM UTC)
==> Retrieving sources...
  -> Downloading Clight-4.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118  100   118    0     0    220      0 --:--:-- --:--:-- --:--:--   220
100 69478    0 69478    0     0  51237      0 --:--:--  0:00:01 --:--:--  122k
==> Validating source files with sha256sums...
    Clight-4.0.tar.gz ... Passed
==> Making package: clightd 4.0-2 (Fri 22 May 2020 10:15:37 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found Clightd-4.0.tar.gz
==> Validating source files with sha256sums...
    Clightd-4.0.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting Clightd-4.0.tar.gz with bsdtar
==> Starting prepare()...
==> Sources are ready.
==> Making package: clightd 4.0-2 (Fri 22 May 2020 10:15:39 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
-- The C compiler identification is GNU 10.1.0
-- Check for working C compiler: /sbin/cc
-- Check for working C compiler: /sbin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /sbin/pkg-config (found version "1.6.3") 
-- Checking for modules 'libudev;libmodule>=5.0.0'
--   Found libudev, version 245
--   Found libmodule, version 5.0.0
-- Checking for module 'polkit-gobject-1'
--   Found polkit-gobject-1, version 0.116
-- Checking for one of the modules 'libelogind;libsystemd>=221'
-- Checking for modules 'x11;xrandr'
--   Found x11, version 1.6.9
--   Found xrandr, version 1.5.2
-- GAMMA support enabled
-- Checking for modules 'x11;xext'
--   Found x11, version 1.6.9
--   Found xext, version 1.3.4
-- DPMS support enabled
-- Checking for module 'x11'
--   Found x11, version 1.6.9
-- SCREEN support enabled
-- Checking for module 'ddcutil>=0.9.5'
--   Found ddcutil, version 0.9.8
-- DDC support enabled
-- Checking for module 'libsystemd'
--   Found libsystemd, version 245
-- Configuring done
-- Generating done
-- Build files have been written to: /home/simon/.cache/yay/clightd/src/Clightd-4.0/build
Scanning dependencies of target clightd
[  6%] Building C object CMakeFiles/clightd.dir/src/main.c.o
[ 12%] Building C object CMakeFiles/clightd.dir/src/modules/backlight.c.o
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/backlight.c: In function ‘receive’:
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/backlight.c:185:9: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  185 |         read(sc->smooth_fd, &t, sizeof(uint64_t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 18%] Building C object CMakeFiles/clightd.dir/src/modules/bus.c.o
[ 25%] Building C object CMakeFiles/clightd.dir/src/modules/dpms.c.o
[ 31%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/tty.c.o
[ 37%] Building C object CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o
[ 43%] Building C object CMakeFiles/clightd.dir/src/modules/gamma.c.o
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/gamma.c: In function ‘receive’:
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/gamma.c:76:9: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   76 |         read(smooth_fd, &t, sizeof(uint64_t));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 50%] Building C object CMakeFiles/clightd.dir/src/modules/idle.c.o
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/idle.c: In function ‘receive’:
/home/simon/.cache/yay/clightd/src/Clightd-4.0/src/modules/idle.c:107:17: warning: ignoring return value of ‘read’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  107 |                 read(msg->fd_msg->fd, &t, sizeof(uint64_t));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 56%] Building C object CMakeFiles/clightd.dir/src/modules/screen.c.o
[ 62%] Building C object CMakeFiles/clightd.dir/src/modules/sensor.c.o
[ 68%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/als.c.o
[ 75%] Building C object CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o
[ 81%] Building C object CMakeFiles/clightd.dir/src/modules/signal.c.o
[ 87%] Building C object CMakeFiles/clightd.dir/src/utils/polkit.c.o
[ 93%] Building C object CMakeFiles/clightd.dir/src/utils/udev.c.o
[100%] Linking C executable clightd
/sbin/ld: CMakeFiles/clightd.dir/src/modules/backlight.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/backlight.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/bus.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/bus.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms_plugins/tty.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms_plugins/tty.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/dpms_plugins/xorg.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/gamma.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/gamma.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/idle.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/idle.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/screen.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/screen.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensor.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensor.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensors/als.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensors/als.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/sensors/camera.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/signal.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/modules/signal.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/utils/polkit.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/utils/polkit.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/utils/udev.c.o:(.bss+0x0): multiple definition of \`udev'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x0): first defined here
/sbin/ld: CMakeFiles/clightd.dir/src/utils/udev.c.o:(.bss+0x8): multiple definition of \`bus'; CMakeFiles/clightd.dir/src/main.c.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/clightd.dir/build.make:314: clightd] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/clightd.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: clightd`

(and I don't know why github won't format the thing proprely despite me espcaping all the "\`"...)

**Comment by FedeDP** [comment]
Hi! Thanks for opening the issue!
Can you try to install clightd-git?
It seems like a Clightd bug that is now exposed with newest gcc (it was an hidden problem with older gcc I guess). If you're concerned about stability, note that clightd-git will soon be tagged as clightd 4.1 :)

**Comment by simony2222** [comment]
`clightd-git` installed fine !
I guess I will stay with this one then switch to `clightd 4.1` once it's out.
Thank you very much !

**Comment by FedeDP** [comment]
Great to hear!! You are welcome, thanks again for taking the time to open this issue!

**Comment by FedeDP** [comment]
Hi @simony2222 !
Clightd 4.1 is now released and available on aur: https://aur.archlinux.org/packages/clightd/ .
