### ISSUE TITLE
[BUG] I can't install clight from aur

### ISSUE THREAD

**Issue by RezaSh13** [FedeDP/Clight#133]
I can't install clight from aur, it's need ddcutil>=0.9.5 but but this package no longer exists 

manjaro

**Comment by FedeDP** [comment]
Ddcutil has been moved to archlinux repository thus it is no longer available on aur. Hopefully manjaro will ship it too in its repositories!

**Comment by RezaSh13** [comment]
Unfortunately, fortunately, like the  Persepolis Download Manager, it has been removed from Aur and entered the Arch Linux repository. but when manjaro will ship it too in its repositories! I do not know...
