### ISSUE TITLE
[BUG] get_screen_brightness(): Input/output error

### ISSUE THREAD

**Issue by mirfatif** [FedeDP/Clight#145]
Refer to https://github.com/FedeDP/Clight/issues/139

**Clight version the issue has been seen with:**
> 4.0

**Used distribution:**
> Ubuntu 20.04

**Describe the bug**

When system boots and `clightd` (`systemd`  service enabled) starts, it throws error:
```
~$ journalctl -u clightd
...
Aug 09 17:14:17 irfan-Inspiron-5521 clightd[790]: Setting Pixel Format: Device or resource busy
```

And at the same time `clight`:
```
...
(D)[17:14:17]{bus.c:279}	get_screen_brightness(): Input/output error
...
```
`clight` no more responds to events. Neither `busctl --expect-reply=false --user call org.clight.clight /org/clight/clight org.clight.clight Calibrate` works. Trying to enter dimmed state for the first time, it fails. But later on cursor movement or power event, it enters dimmed state and remains there forever, whatever happens. Once I kill `clight` and restart, it starts functioning normally.

This happens most of the times, but not always. I don't know exactly with what conditions, looks random.

**Comment by FedeDP** [comment]
Any news on this?

**Comment by mirfatif** [comment]
> Any news on this?

Sorry for the delayed response. Actually I haven't observed the problem after updating to Clight 4.1 (was already on Clightd 4.2). Closing this for the moment. If I find something related, I'll return back with information.
Thanks.
