### ISSUE TITLE
[BUG] Clight asks for clightd 4.3

### ISSUE THREAD

**Issue by coldspark29** [FedeDP/Clight#153]
**Clight version the issue has been seen with:**
> r715.767e184-1

**Used distribution:**
> Manjaro

**Describe the bug**
``Clightd must be updated. Required version: 4.3.`` is shown although I have used the latest git version.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this bug report! 
Are you running clightd-git too?

**Comment by coldspark29** [comment]
Yes, I now went back to the distro’s version. That one works, but I can‘t run the wizard there. With the git version running the wizard works.

**Comment by FedeDP** [comment]
Did you restart your system once installed clight-git and clightd-git?

**Comment by coldspark29** [comment]
No I obviously didn't because it works now :)
