### ISSUE TITLE
[BUG] Keyboard backlight is not reacting

### ISSUE THREAD

**Issue by coldspark29** [FedeDP/Clight#154]
**Clight version the issue has been seen with:**
> 4.1

**Used distribution:**
> Manjaro

**Describe the bug**
The keyboard doesn't react, but the backlight does. It is supported well by KDE Plasma under battery settings, so it should not be a problem. I have a Thinkpad X380 Yoga.

**Comment by FedeDP** [comment]
This is weird; which clight commit is built? 
There was a bug in clight 4.1 that has been fixed on clight-git package. My dell xps kbd backlight is now working fine.

**Comment by coldspark29** [comment]
Oh yes it is version 4.1. It should be version 4.2 but on the AUR page there is still ``Clight-4.1.tar.gz``
