### ISSUE TITLE
[BUG] Example for custom modules possible outdated

### ISSUE THREAD

**Issue by coldspark29** [FedeDP/Clight#156]
**Clight version the issue has been seen with:**
> 4.2

**Used distribution:**
> Manjaro

**Describe the bug**
I wanted to build the nightmode module according to the Wiki. Also tried the nightmode.skel, but I get a segmentation fault. For getting the system() function to recognize I needed ``#include <stdlib.h>`` but I also get ``exptected unqualified-id``. Could it be that the PubSub commands have changed or am I missing another include?

![image](https://user-images.githubusercontent.com/19779511/96241016-e9b47080-0fa1-11eb-841b-caab86a50853.png)

**Comment by FedeDP** [comment]
Hi, thanks for opening this bug report!
You are surely right about stdlib.h include, thanks for pointing it out!
But i don't get the other issue; i am able to successfully build the module with no problem.

**Comment by coldspark29** [comment]
I tried to test it in the shell and it did not change the theme

**Comment by coldspark29** [comment]
Everything works since I have got the git version to work :)
