### ISSUE TITLE
a way to inhibit clight when using a photo manager ?

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#179]
Is there a cli command to inhibit clight when using a photo manager ?

Thanks

**Comment by FedeDP** [comment]
Hi! What do you intend to inhibit? Clight autocalibration? Dimming?
Btw right click on desktop file and clight provides some actions ready for you!

**Comment by promeneur** [comment]
I did not get any desktop file on my desktop. Where is it supposed to be ?

I want just the same thing which happens when I display a video with vlc or firefox.

**Comment by FedeDP** [comment]
> I want just the same thing which happens when I display a video with vlc or firefox.

Ok! if you look for clight in your DE menu you should find it! Then right click on it and select "Pause Screen Dimmer"!

**Comment by promeneur** [comment]
It's not exactly what I need.

I want to write a script like this.

pause clight (no brigthness,no gamma management)
launch digikam
unpause clight

**Comment by promeneur** [comment]
With redshift I had this script

pkill -usr1 redshift (trun off)
digikam
pkill -usr1 redshift (turn on)

**Comment by FedeDP** [comment]
Ok! In clight you can do:
```
busctl --expect-reply=false --user call org.clight.clight /org/clight/clight org.clight.clight Pause "b" true
digikam
busctl --expect-reply=false --user call org.clight.clight /org/clight/clight org.clight.clight Pause "b" false
```

**Comment by promeneur** [comment]
Wow, very techie ! Thanks.
