### ISSUE TITLE
Config to set absolute minimum brightness

### ISSUE THREAD

**Issue by min050820** [FedeDP/Clight#18]
Please add a config to let users choose minimum/maximum brigtness instead of just 0 and detected maximum value. Some laptops (a.k.a. mine) completely shuts LCD down when they are told to set brightness to 0, causing really (a lot!) troubles.

It would be ideal to be able to set valued used for interpolating, but just clamp would be okay.

**Comment by FedeDP** [comment]
> It would be ideal to be able to set valued used for interpolating, but just clamp would be okay.

Well, you can :)
Not only that, you can set a different curve for each AC states (on battery and on AC), have a look here: https://github.com/FedeDP/Clight#polynomial-fit
