### ISSUE TITLE
ambient gamma ?

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#180]
A question about "ambient gamma".

I heard that some tv adapt brightness and color, using icc profile and the ambient brightness, to get the best color.

Is it the case of "ambient gamma" ?

**Comment by FedeDP** [comment]
Hi! Somewhat: ambient_gamma enables clight to match screen temperature to ambient brightness, ie: the lower the ambient brightness, the lower the screen temperature.
This feature helps to reduce eyestrain in any occasion, not only during the night.

**Comment by promeneur** [comment]
Eyestrain occurs also viewing a video. Is "ambient gamma" turned off viewing a video ?

**Comment by FedeDP** [comment]
>  Is "ambient gamma" turned off viewing a video ?

No it is not; it follows backlight changes, thus when backlight calibration is enabled, ambient gamma does its job.
