### ISSUE TITLE
clight report brightness 0 % but brightness is 24 %

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#183]
clight 4.3, clightd 5.2

clight-gui reports "brightness 0 %" in its contextual menu.

i opened a bug report at clight-gui 

see the report

https://github.com/nullobsi/clight-gui/issues/8#

**Comment by FedeDP** [comment]
Hi! It is working fine for me.
Can you share clight.log?

**Comment by promeneur** [comment]
[clight.log](https://github.com/FedeDP/Clight/files/5936602/clight.log)

**Comment by promeneur** [comment]
remember i use master branch.

**Comment by FedeDP** [comment]
Btw you are setting some wrong config values:

> (W)[08:35:14]{opts.c:284}	Wrong AC frames value. Resetting default value.
(W)[08:35:14]{opts.c:288}	Wrong BATT frames value. Resetting default value.

I need a verbose log, enable verbose in config or through --verbose cmd line switch.

**Comment by promeneur** [comment]
[clight.log](https://github.com/FedeDP/Clight/files/5936683/clight.log)

**Comment by FedeDP** [comment]
I think i have found the root cause: it is a bug in Clightd: to emit Changed signals on each backlight step it monitors udev; but for external monitors only setup, udev won't report anything (it only sees internal backlight on laptops).
Thus your Clight was not receiving any backlight update signal.
I will fix this asap.

**Comment by FedeDP** [comment]
I have no such environment (ie: a desktop pc) but hopefully latest Clightd should fix the issue. Care to test?

**Comment by promeneur** [comment]
Problem solved. What about

(W)[13:50:55]{opts.c:284}	Wrong AC frames value. Resetting default value.
(W)[13:50:55]{opts.c:288}	Wrong BATT frames value. Resetting default value.

**Comment by FedeDP** [comment]
Number of captures must be between 1 and 20! Check your config.
I added a comment in clight conf file to highlight the limit, thanks!

**Comment by promeneur** [comment]
i use 5 captures on AC and 5 on Battery.

**Comment by FedeDP** [comment]
Can you share your clight.conf?

**Comment by promeneur** [comment]
[clight.conf.log](https://github.com/FedeDP/Clight/files/5936935/clight.conf.log)

**Comment by FedeDP** [comment]
WHoopsie that was another stupid bug! Fixed in latest commit!

**Comment by promeneur** [comment]
> WHoopsie that was another stupid bug! Fixed in latest commit!

Problem solved with last master branch
