### ISSUE TITLE
[FEATURE REQ] support older versions of systemd

### ISSUE THREAD

**Issue by lgbaldoni** [FedeDP/Clight#184]
Would it be very problematic to backport Clight for lder systemd releases?
Many stable (as in non rolling) distros are stuck at 234.

**Comment by FedeDP** [comment]
Hi! Clight master already depends on systemd >= 234 (i recently added back support for opensuse 15.2 that ships it, fixing another feature req :)

**Comment by FedeDP** [comment]
(I can't go lower than 234 because in 234 a PR of mine (https://github.com/systemd/systemd/pull/5753) was merged and it is needed by Clight.
Anyway i think that supporting a 4yrs old systemd is more than enough :)

**Comment by lgbaldoni** [comment]
Sorry, I had missed the commit that lowered it from 237: excellent news!

**Comment by FedeDP** [comment]
Btw i plan a clight and clightd release soon!
