### ISSUE TITLE
Info, a package for openSuse 15.2 is now supplied

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#185]
Luigi Baldoni (alois) informed me that he created a package for clight 4.2 and clightd 5.1 which are compliant with openSuse 15.2 !

I hope we did not work for nothing.

see

https://build.opensuse.org/package/show/hardware/Clight

**Comment by FedeDP** [comment]
That's super great! I plan to do a release asap, maybe next weekend, with latest bugfixes (and to ease packaging!).
Thank you!

**Comment by promeneur** [comment]
Ok I am very impatient.

Thanks
