### ISSUE TITLE
viewing a video, adjust gamma ?

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#187]
clight 4.2
clightd 5.1

ambient gamma enabled

If I view a video then gamma is not restored to 6500 K and still adjusted.
Ambient gamma or not who wants to see a video with red filter and not real colors ?

Please give the choice with some setting as these

ambient_gamma_in_case_of_viewing_video_do_not_adjust_gamma_restore_it_to_6500_K = yes
no_ambient_gamma_in_case_of_viewing_video_do_not_adjust_gamma_restore_it_to_6500_K = yes

Thanks

**Comment by FedeDP** [comment]
Hi! Dbus API comes in help once more!
`busctl --user set-property org.clight.clight /org/clight/clight/Conf/Gamma org.clight.clight.Conf.Gamma NightTemp "i" 6500`

Then, to reset previous value:
`busctl --user set-property org.clight.clight /org/clight/clight/Conf/Gamma org.clight.clight.Conf.Gamma NightTemp "i" 4000`

In last command, just remember to change "4000" to whatever value you set in config file!

**Comment by promeneur** [comment]
Thanks. Very kind.

It would be a good idea to add this to your wiki. No ?

**Comment by promeneur** [comment]
This is to set Night temp. But we need to pause gamma adjusting and resume it.

**Comment by FedeDP** [comment]
> This is to set Night temp. But we need to pause gamma adjusting and resume it.

Well once day and night gamma have same value, there won't be anything that changes gamma :)

**Comment by FedeDP** [comment]
> It would be a good idea to add this to your wiki. No ?

I am planning to ask community for help; i don't need much help for code, but all auxiliar things like improve wiki, keep API doc up to date, update various completions scripts... 
I would love to let more people join me and help me deliver the best software i can!

**Comment by promeneur** [comment]
I think about ambient gamma. If ambient gamma is not paused then 10 mn later it will adjust gamma. No ?

**Comment by FedeDP** [comment]
You are right!
Ambient gamma works together with backlight calibration; thus if you mix this call with #186 method to disable autocalibration, nobody will touch your gamma anymore :)

**Comment by promeneur** [comment]
>> You are right!
>> Ambient gamma works together with backlight calibration; thus if you mix this call with #186 method to disable >> autocalibration, >> nobody will touch your gamma anymore :)

What i want is

case "ambient gamma"

- keep brightness adjusting
- pause color temperature adjusting
- launch an app
- quit app
- resume color temperature adjusting

 I fear that disabling "autocalibrating" disables brightness adjusting. No ?
