### ISSUE TITLE
switching from ambient gamma to no ambient gamma => gamma not restored to 6500 K

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#188]
clight 4.2
clightd 5.1

If i switch from ambient gamma to no ambient gamma then gamma is not restored to 6500 K.
I waited for the 10 mns.

**Comment by FedeDP** [comment]
Yes because no message is sent to require current temp.
I will fix this!

**Comment by FedeDP** [comment]
It should now work with latest clight and clightd!
