### ISSUE TITLE
Allow light correction with configfile

### ISSUE THREAD

**Issue by asm0dey** [FedeDP/Clight#19]
For me default clight settings are to bright. I would prefer to have way to correct settings.
i.e. right now clights sets brightness 3600 for me, but I would prefer 2200.

**Comment by FedeDP** [comment]
Hi, thanks for your report. You can actually change backlight-to-ambient-brightness function to better suit your preference, have a look at config file in /etc/default/clight.conf: https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L71.
As you can see, you can even set 2 different curves for AC state.

**Comment by asm0dey** [comment]
Thank you! It can serve even better than "hard" adjustment!

**Comment by ModDM** [comment]
If you make a line chart of it in your spreadsheet program, you can display the curve graphically and play with the numbers and see the curve changes:

![Screenshot from 2019-08-14 21-08-14](https://user-images.githubusercontent.com/15093029/63049038-153c5680-bed8-11e9-833b-48bc03fc8bb0.png)

**Comment by ModDM** [comment]
Question: Is it also allowed to add curve points?

**Comment by FedeDP** [comment]
Right now it is not possible.
But there is no theoretical limit in code; it can be easily done. 

Can you open another issue/feature request?
Maybe explain why you'd think it could improve your experience!

**Comment by ModDM** [comment]
Sure, after testing some days / afternoons / evenings etc. I will have more experience with the curve and then I am better able to describe why / which way etc.
