### ISSUE TITLE
screen_sysname = "intel_backlight"   ?

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#191]
Can you explain what is this setting "screen_sysname = "intel_backlight" "?

I get an Intel i915 graphical adapter.

**Comment by FedeDP** [comment]
It is the interface on which Clight should set backlight, for laptops internal backlight.
Some laptops expose multiple syspaths under `/sys/class/backlight/`, and some of these paths do not work well. 
The option allows to select an interface to use.
If left empty, first found interface is used.
