### ISSUE TITLE
[BUG] Clight don't resume keyboard with the right level of light

### ISSUE THREAD

**Issue by baydam** [FedeDP/Clight#205]
**Clight version the issue has been seen with:**
> clight 4.4-5 , clightd 5.2-3

**Used distribution:**
> Arch Linux

**Describe the bug**
On my Lenovo laptop I have three level of light `[0, 1, 2]` and I used to set it at `1` under a dark environment. 
The keyboard backlight is set to off after a period of time using clight, but after every backlight resume the light is set to the maximum level like `2`  

**Expected behavior**
I would like to see clight remembering the previous keyboard backlight level and restore it

**Comment by FedeDP** [comment]
Hi! Thanks for opening this bug report!
Clight uses reverse monitor backlight curve for keyboard backlight; thus, on low screen backlight it sets maximum keyboard backlight.
In your case, this means that in a dark environment it will set 2.  
I don't really want to add complexity to keyboard module; i want to keep this feature as simple as possible, as in most cases 2 is a good value. Moreover, keyboards often (always?) only have 3 backlight levels, thus a more granular solution is quite over engineered.

Finally, note that Clightd supports "changed" udev events for keyboard; this means that theoretically, Clightd is able to tell Clight that user has changed keyboard backlight, and this will fix your issue; unfortunately, it seems that udev signal is not emitted by keyboard backlight drivers.
See this comment: https://github.com/FedeDP/Clightd/blob/master/src/modules/keyboard.c#L104.
