### ISSUE TITLE
[BUG] monitor override DBus interface not working?

### ISSUE THREAD

**Issue by nullobsi** [FedeDP/Clight#222]
**NOTE:** Please try to upgrade Clight if not running on latest release, before reporting a bug!

**Clight version the issue has been seen with:**
> latest master

**Used distribution:**
> arch linux

**Describe the bug**
I think I finished adding monitor overrides to Clight GUI, but it appears nothing is saving! Similar to the other issue I reported, I am able to call Set and List no problem, but while Set returns no error, when I try to List again, the monitor overrides I set are not being returned...

**Expected behavior**
After calling Set, a call to List should return the new monitor overrides.

**To Reproduce**
```sh
busctl --user call org.clight.clight /org/clight/clight/Conf/MonitorOverride org.clight.clight.Conf.MonitorOverride Set sadad LF80D0028500 11 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 11 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1
busctl --user call org.clight.clight /org/clight/clight/Conf/MonitorOverride org.clight.clight.Conf.MonitorOverride List
```

Please attach a Clight verbose log too!
it seems the log doesn't have much useful info, but here it is
[clight.log](https://github.com/FedeDP/Clight/files/6996288/clight.log)

**Comment by FedeDP** [comment]
Uh thanks for opening the bug report! It is most probably due to the fact that the map is left NULL if no monitor override option is present in config file.
I will fix it asap, in the meantime you can try just uncommenting a monitor override option in config file and it should work!
