### ISSUE TITLE
[BUG] sigsegv when running `qdbus org.kde.KWin /Effects activeEffects`

### ISSUE THREAD

**Issue by NICHOLAS85** [FedeDP/Clight#224]
**NOTE:** Please try to upgrade Clight if not running on latest release, before reporting a bug!

**Clight version the issue has been seen with:**
> Latest git (8047e69d85ec28e2c41c322b089506fa354cac5e)

**Used distribution:**
> Bedrock Linux 0.7.21beta2 Poki, Debian Testing stratum

**Describe the bug**
Occasionally Clight would abort while I was using my computer, I found that a script I run was causing Clight to crash. I was able to narrow it down to the `qdbus org.kde.KWin /Effects activeEffects` command. This is a KDE specific command. This bug would not always happen if Clight was already running but is easy to reproduce when Clight was recently launched.

**Expected behavior**
Clight not to crash

**To Reproduce**
Launch Clight and quickly after run `qdbus org.kde.KWin /Effects activeEffects`

Logs:
[clightlog.txt](https://github.com/FedeDP/Clight/files/7093749/clightlog.txt)
[strace.txt](https://github.com/FedeDP/Clight/files/7093750/strace.txt)

**Comment by NICHOLAS85** [comment]
Sure, to build in debug mode do I just change `-DCMAKE_BUILD_TYPE="Release"` to `-DCMAKE_BUILD_TYPE="Debug"` in the build script?

**Comment by NICHOLAS85** [comment]
Heres the output at crash:
```
Program received signal SIGSEGV, Segmentation fault.
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101     ../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
```

**Comment by FedeDP** [comment]
Ok can you execute "bt" in the gdb shell after the crash? And paste here the output! Thank you!

**Comment by NICHOLAS85** [comment]
```
(gdb) bt
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x0000555555567dd2 in inhibit_parse_msg (m=0x5555556426b0)
    at /home/nicholas/github/built/Clight/src/modules/interface.c:330
#2  0x0000555555567820 in receive (msg=0x7fffffffb2b0, userdata=0x0)
    at /home/nicholas/github/built/Clight/src/modules/interface.c:211
#3  0x00007ffff7f936f3 in run_pubsub_cb () from /lib/libmodule.so.5
#4  0x00007ffff7f92e71 in recv_events () from /lib/libmodule.so.5
#5  0x00007ffff7f930dd in modules_ctx_loop_events () from /lib/libmodule.so.5
#6  0x000055555555f8fc in main (argc=2, argv=0x7fffffffb448) at /home/nicholas/github/built/Clight/src/main.c:45
```

**Comment by FedeDP** [comment]
It seems Clight dies here:
```
      const char *interface = sd_bus_message_get_interface(m);
        
        for (int i = 1; i <= 2; i++) {
            if (!strcmp(interface, sc_interface)
```
It seems that "interface" is NULL there. I did not know that a message could be emitted with no interface (?).
I pushed a commit, can you try updating clight and see if crash persists?

**Comment by NICHOLAS85** [comment]
After updating, it looks like the crash no longer persists!

**Comment by FedeDP** [comment]
Thank you very much for the debug session!

**Comment by NICHOLAS85** [comment]
of course and thanks for the quick fix
