### ISSUE TITLE
[BUG] no Clight item in kde menu

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#230]
**NOTE:** Please try to upgrade Clight if not running on latest release, before reporting a bug!

**Clight version the issue has been seen with:**
> ...4.7

**Used distribution:**
> ...openSuse 15.3

**Describe the bug**

After compiling, I installed clight as root with "make install".

No item relative to Clight is installed in KDE menu.

**Expected behavior**

An item is installed in the KDE menu.

**To Reproduce**
Steps to reproduce the behavior.

Please attach a Clight verbose log too!

**Comment by FedeDP** [comment]
Hi! thanks for opening this bug report! Can you share output of
`ls /usr/share/applications/clightc.desktop`?

**Comment by promeneur** [comment]
@localhost:~> ls /usr/share/applications/clightc.desktop
/usr/share/applications/clightc.desktop
@localhost:~>

**Comment by promeneur** [comment]
Hello 

Clight is there again in kde menu !
