### ISSUE TITLE
[FEATURE REQ] add sunrise and sunset offsets

### ISSUE THREAD

**Issue by elypter2** [FedeDP/Clight#237]
**Is your feature request related to a problem? Please describe.**
 the indoor lighting conditions do not always match up with natural sunlight or some people want the day on the display appear longer or shorter than the the actual daylight

**Describe the solution you'd like**
an offset would allow you to still depend on the sunlight but deviate from it by a custom amount.

**Describe alternatives you've considered**
a sunrise and sunset offset that can have a positive or negative amount of minutes as values.

**Comment by FedeDP** [comment]
Hi! That's a neat idea, thanks for the suggestion!
It is a very simple implementation yet I think it can be useful.
I will implement this :)

**Comment by elypter2** [comment]
thanks

**Comment by FedeDP** [comment]
Hi! This is now implemented in master :)
