### ISSUE TITLE
Update documentation by adding the following packages for debian 11

### ISSUE THREAD

**Issue by faan11** [FedeDP/Clight#239]
Hi,

The sofware also needs the following packages in order to compile with Debian 11:

libjpeg-dev libudev-dev polkit-gobject-1-dev libddcutil-dev dh-autoreconf bash-completion fish libdbus-1-dev

**Comment by FedeDP** [comment]
Hi! Thanks for taking the time to check Clight and Clightd deps!  
Indeed most of all should already be listed; for Clightd i see:
> $ sudo apt install build-essential pkg-config cmake libsystemd-dev libxrandr-dev libxext-dev policykit-1 **libpolkit-gobject-1-dev** **libjpeg-dev** libusb-dev libwayland-dev libdrm-dev **libddcutil-dev** **libdbus-1-dev**

While, for Clight, i see:
> $ sudo apt install build-essential cmake libsystemd-dev libpopt-dev libconfig-dev libgsl-dev

Note, moreover, that `bash-completion fish` are optional deps for Clight!

I see i missed `libdbus-1-dev` for Clight; again for Clight, `fish` opt dep was missing.
For Clightd, libudev-dev is missing!

Thank you very much, i updated both Clight and Clightd wiki pages!
