### ISSUE TITLE
[BUG] clight: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by coldspark29** [FedeDP/Clight#243]
**Clight version the issue has been seen with:**
> 409b255cf2608388bb0d794b7ad8b746b37acf72

**Used distribution:**
> Manjaro

**Describe the bug**
I just upgraded clight from the AUR and am getting the following message: 

clight can't be executed. Error message
clight: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory

**Comment by FedeDP** [comment]
Hi! Most probably you upgraded gsl and now Clight needs to be built again. Can you try to re-install Clight?

**Comment by coldspark29** [comment]
I already tried that. Doesn't help. Weird.

**Comment by FedeDP** [comment]
Mmh what's the output of: 
ls /use/lib/libgsl*
?

**Comment by coldspark29** [comment]
It's .so.27 and not .so.25. It should be automatically rebuilt with that, shouldn't it?

/usr/lib/libgsl.so /usr/lib/libgsl.so.27 /usr/lib/libgsl.so.27.0.0 /usr/lib/libgslcblas.so /usr/lib/libgslcblas.so.0 /usr/lib/libgslcblas.so.0.0.0

**Comment by FedeDP** [comment]
Yep, that's weird! Perhaps Clight is being built with a cached makefile that links to old so.25?
What about:
pkg-config --libs gsl
?

**Comment by coldspark29** [comment]
Ah I got it. There was still the old version installed in /usr/local, which I manually compiled. Thanks for the help :)
