### ISSUE TITLE
[question] is it possible that some webcam auto-brighten the images they capture?

### ISSUE THREAD

**Issue by flying-x** [FedeDP/Clight#250]
I am using logitech c922 pro stream webcam. It seems that clight's sensor output is not changing much (between 89%-91%) when I turn on/off lights & blinds in my room. Is it possible that the cam is auto-brightening the images so that clight can't properly work?

Any suggestions on how to find out the potentially issues?

**Comment by FedeDP** [comment]
Hi! Yeah that could happen!
Basically, Clightd sets Webcam defaults values before doing any capture. Therefore, if your webcam defaults have auto brightness or some other wizardry active, you'll get the behavior.
But, good thing is Clightd allows you to manually specify configurations for sensors: https://github.com/FedeDP/Clightd/wiki/Sensors#camera-1

Clight passes the Sensor.settings conf option to Clightd for this reason :)

**Comment by flying-x** [comment]
it is working after I manually did the following:
![image](https://user-images.githubusercontent.com/22962929/169542245-04a392d6-5734-4c89-9eee-250280c1a504.png)
