### ISSUE TITLE
[FEATURE REQ] Add option to delay DDC communications after wakeup

### ISSUE THREAD

**Issue by Bonnee** [FedeDP/Clight#252]
**Is your feature request related to a problem? Please describe.**
My Dell monitor has a firmware bug that kills it upon wakeup, requiring a hard power cycle.

**Describe the solution you'd like**
Inspired by [lunar's FAQ](https://lunar.fyi/faq#firmware-bugs) I propose a similar feature to delay communications after wakeup. I don't know if this will actually fix my issue, but if lunar's got the feature I guess it's working for someone.

**Describe alternatives you've considered**
Since I don't even know if this would work, I haven't thought about alternatives

**Comment by FedeDP** [comment]
Ehy! Thanks for opening this issue!
Clight has a [`resumedelay`](https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L18) option for issues like this one ;) Care to try?

**Comment by Bonnee** [comment]
Ok I totally missed that feature. Seems exactly what I wanted!
