### ISSUE TITLE
[Question] monitor does not support DDC. Will it work?

### ISSUE THREAD

**Issue by aas2116** [FedeDP/Clight#261]
**Is your feature request related to a problem? Please describe.**
Id like to use clight but my monitor does not support ddc. Wondering if it will still work or if DDC is the only method to change brightness. 

**Describe the solution you'd like**
Does clight support alternative methods to adjust brightnes (e.g.  xrandr)?

**Describe alternatives you've considered**
I have built a simple bash script which adjusts brightness using xrandr using a cronjob based on time of day, but it does not use any input (and therefore is not great).

**Comment by FedeDP** [comment]
Hi! Well, is your monitor an external one, right? In that case, if DDC is not supported, there is not much we can do...
I do not support xrandr right now, but i might think about adding support for it in Clightd!
Can you open a feature request on Clightd to track it? :) Thank you very much!

**Comment by FedeDP** [comment]
Hi! I am working on a Clightd branch for this; i think it is very cool indeed (and i use it myself on my TV, since it does not support DDC protocol!)
You can follow its development here: https://github.com/FedeDP/Clightd/tree/new/backlight_backends

**Comment by FedeDP** [comment]
The Clightd feature is now available in master (not yet released). Care to test?
Thank you very much!

**Comment by FedeDP** [comment]
The feature was released with Clightd [5.8](https://github.com/FedeDP/Clightd/releases/tag/5.8), i will close this one!
