### ISSUE TITLE
Good news, soon a standard package in openSUSE

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#266]
Now clicht and clightd are experimental packages in openSUSE in the hardware repo.

May be soon we get standard packages.

![opensuse_clight](https://user-images.githubusercontent.com/240424/208909492-0a04d780-2279-4fba-bc5d-6a39f5f182b7.png)
![opensuse_clightd](https://user-images.githubusercontent.com/240424/208909943-29a36323-5806-4a08-855c-1f7488dd174b.png)

**Comment by FedeDP** [comment]
Just wow 😲

**Comment by FedeDP** [comment]
Closing :) thanks for the info and feel free to reopen if you got any news!
Thank you very much!
