### ISSUE TITLE
[question] how to uninstall clight ?

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#267]
I want to use openSUSE packages.
I must uninstall clight.

Furthermore, I tried “sudo make uninstall”.
This does not work.

I did not find in the wiki anything about uninstalling.

**Comment by FedeDP** [comment]
Hi! Sorry for the late response!
I think you are looking for: https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall :) 
This is just a CMake missing feature IMHO!

**Comment by FedeDP** [comment]
I added a note in the FAQ: https://github.com/FedeDP/Clight/wiki/FAQ#how-to-uninstall-it

**Comment by promeneur** [comment]
thanks
