### ISSUE TITLE
Enable/disable gamma correction at night

### ISSUE THREAD

**Issue by mmguar** [FedeDP/Clight#268]
I might have missed the ability to do so in clight/clightd, but I was not able to find a way to restore gamma to DayTemp at night, which is a common use case, for example when watching a movie.
I used dbus to change NightTemp to the value of DayTemp as a quick solution, and I added the functionality to the gui, but it would be nice to have a boolean NightPause property available through dbus, as other solutions require storing the original value of NightTemp, to be able to restore it.

**Comment by FedeDP** [comment]
Hi! Latest master exposes `org.clight.clight.Conf.Gamma.Toggle` method to toggle between states' temps, like:
`busctl --user call org.clight.clight /org/clight/clight/Conf/Gamma org.clight.clight.Conf.Gamma Toggle`
;)

**Comment by FedeDP** [comment]
Moreover, desktop file exposes a ToggleGamma action now!

**Comment by FedeDP** [comment]
Wiki page has been updated accordingly: https://github.com/FedeDP/Clight/wiki/Api#bus-methods-3
