### ISSUE TITLE
[BUG] ALS detected but doesn't really work

### ISSUE THREAD

**Issue by theGeekyLad** [FedeDP/Clight#277]
**Clight version the issue has been seen with:**
>  4.9-8069945

**Used distribution:**
> Arch Linux (6.2.9-arch1-1)

**Describe the bug**
Great work with the project! I see that the brightness auto-increases when the window is darker and vice versa when lighter. Nonetheless, though clight detects my ALS (through `busctl call org.clightd.clightd /org/clightd/clightd/Sensor/Als org.clightd.clightd.Sensor Capture "sis" "" 5 ""`), I don't see any visible change in the brightness level when I'm on a certain window and the ambient light levels fluctuate (checked by covering the ALS with a finger). I can confirm that the sensor does report different values when covered with a finger and when not with this command - `cat /sys/bus/iio/devices/iio\:device0/in_illuminance_raw`.

**Expected behavior**
As the ambient light levels (of my room) fluctuate, the brightness must vary (e.g. when the table top lamp is turned on).

**To Reproduce**
Ran `clight` and `clight -d /dev/iio:device0`.

**Clight Log** [clight-log.txt](https://github.com/FedeDP/Clight/files/11243789/clight-log.txt)

**Comment by FedeDP** [comment]
Hi! Thank you for the kind words :)
A similar issue is being tracked on Clightd: https://github.com/FedeDP/Clightd/issues/88
I shared some commands whose output is really helpful. I'd move the discussion over there since this is 100% a clightd problem ;)
