### ISSUE TITLE
[BUG] Config file: file I/O error at line 0

### ISSUE THREAD

**Issue by promeneur** [FedeDP/Clight#290]
**NOTE:** Please try to upgrade Clight if not running on latest release, before reporting a bug!

**Clight version the issue has been seen with:**
> ...4.10

**Used distribution:**
> ...openSUSE Tumbleweed

**Describe the bug**

in clight.log we get this error : 

(W)[11:18:58]{config.c:437}	Config file: file I/O error at line 0.

**Comment by FedeDP** [comment]
Hi! Thanks for opening this bug report! Indeed this issue is fixed in master; i need to find the time to make a new release!

**Comment by promeneur** [comment]
OK thanks

**Comment by FedeDP** [comment]
Should be fixed by the just released Clight 4.11!
