### ISSUE TITLE
When clight fails to acquire the camera device, it sets backlight brightness to zero

### ISSUE THREAD

**Issue by Amadiro** [FedeDP/Clight#3]
This can happen when you e.g. start a different application that uses the camera.

Output:

```
Device or resource busy
Average frames brightness: 0.000000.
New brightness value: 0
```

Probably the brightness should never be set to zero.

**Comment by FedeDP** [comment]
Indeed that should definitely is its behaviour.  
This is a bug, thanks for the report!
