### ISSUE TITLE
segmentation fault, loading dimmer if inhibition is disabled

### ISSUE THREAD

**Issue by nick87720z** [FedeDP/Clight#30]
I'm testing this on Lubuntu 16.04, and by some reason gdb is unable to give any useful backtrace here.

EDIT: if inhibition is enabled, it says, that PM inhibition appears to be unsupported, but tries to start dimmer (init is called), then adds its callback. Later inhibition is destroyed, but dimmer is not.

If inhibition is disabled, callback is not added before to destroy unused modules.
UserBus and Inhibit modues are destroyed at this stage, then it crashes (these are messages).

**Comment by FedeDP** [comment]
I need clight verbose log and your conf.  
Is #29 related? Was it opened by mistake?

**Comment by nick87720z** [comment]
Mistake. I wanted to rename it.

**Comment by nick87720z** [comment]
```
Config file /etc/default/clight.conf not found.
Gamma module disabled.
Trying to start Brightness module as its Gamma soft dep was disabled...
Location module disabled.
Location module destroyed.
Gamma module destroyed.
Signal module started.
Bus module started.
UserBus module being started as submodule of Bus...
UserBus module started.
Dpms module disabled.
Dpms module destroyed.
Xorg module started.
Trying to start Dimmer module as its Xorg dependency was loaded...
Inhibit module disabled.
Trying to start Dimmer module as its Inhibit soft dep was disabled...
UserBus module disabled.
UserBus module destroyed.
Inhibit module destroyed.
Ошибка сегментирования (сделан дамп памяти)
```
last message - segmentation fault; LANG=C doesn't work here.

**Comment by FedeDP** [comment]
Can you test with this patch? ( #31 too)

[test.txt](https://github.com/FedeDP/Clight/files/2163971/test.txt)

**Comment by nick87720z** [comment]
Doesn't help. As with inhibit tried to loaded, I looked above in log - it says about missing *.service file.
with no_inhibit it crashes as before.

**Comment by FedeDP** [comment]
This should be proper output:  

> Gamma module disabled.
Trying to start Brightness module as its Gamma soft dep was disabled...
Location module disabled.
Location module destroyed.
Gamma module destroyed.
Signal module started.
Bus module started.
UserBus module being started as submodule of Bus...
UserBus module started.
Dpms module disabled.
Dpms module destroyed.
Xorg module started.
Trying to start Dimmer module as its Xorg dependency was loaded...
Inhibit module disabled.
Trying to start Dimmer module as its Inhibit soft dep was disabled...
UserBus module disabled.
UserBus module destroyed.
Inhibit module destroyed.
Clightd found, version: 2.1.

So, it crashes while initing Clightd module.

**Comment by nick87720z** [comment]
Btw, about log:
everything is default, only these 3 lines:
```
no_dpms = 1
no_inhibit = 1
verbose = 1
```
To stop segfault, it needs either uncomment `no_dimmer = 1` or comment `no_inhibit = 1`.

**Comment by FedeDP** [comment]
My guess is that here: https://github.com/FedeDP/Clight/blob/master/src/bus.c#L257, it is using userbus instead of bus. But userbus in NULL there, as userbus module has been destroyed.  
Why should it use it though, that's quite a mistery.  
Can you please check adding a printf:
`if (userbus == NULL) { printf("Nice"); }`

**Comment by FedeDP** [comment]
I pushed some updates. I don't think they will fix your issue though, but never say never :)

**Comment by FedeDP** [comment]
I fixed some issues spotted by valgrind. Can you test once more with updated master?

**Comment by nick87720z** [comment]
Confirming, no crashes anymore.

**Comment by FedeDP** [comment]
Nice to hear! Thanks for your testing!
