### ISSUE TITLE
[FEATURE REQ] DECREASE BACKLIGHT LEVELS ON AC

### ISSUE THREAD

**Issue by quantavirile** [FedeDP/Clight#305]
**Is your feature request related to a problem? Please describe.**
I get higher brightness levels when AC is connected (i.e. 80-97 brightness range) compared to when the laptop is using BAT in similar lighting condition. This is a problem because higher brightness levels are not safe for eyes.

**Describe the solution you'd like**
Is it possible to limit the brightness levels on AC or at least to match with the BAT levels whether during the day or night in similar lighting condition. I would prefer the levels to crank up when the ambient is bright enough.

**Describe alternatives you've considered**
Limiting the brightness by customizing backlight curves regression points as stipulated in https://github.com/FedeDP/Clight/issues/232. However the solution does not work after restarting clightd "sudo systemctl restart clightd"

The following is a snippet of my sensor module config:
sensor : 
{
  captures = [ 5, 5 ];
  ac_regression_points = [ 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59 ]; 
  batt_regression_points = [ 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59 ];
};

**Note:** I am using clight-gui if maybe it's causing this problem.

**Comment by quantavirile** [comment]
Hello, I've managed to configure Clight using the provided config files without using the Clight GUI app and everything is working as desired. Thanks for this great project because I no longer have to manually adjust my brightness ever again.

**Comment by FedeDP** [comment]
You are welcome and thanks for your kind words!
Also sorry if I did not answer your issue, I am not having much spare time lately :)
