### ISSUE TITLE
Wrong behavior with brightness

### ISSUE THREAD

**Issue by nick87720z** [FedeDP/Clight#32]
EDIT: i did not test it enough.
Brightness changes automatically after start even if all modules are unloaded, with message:
`New brightness pct value: 0.014719`
this value is never same, and seems to be randomly selected from some range, but it doesn't depend on current brightness.

**Comment by nick87720z** [comment]
It appears to be more complicated. Last time i started clight with all modules disabled and screen brightness began oscillate around some very slowly moving point. Another case, when it may appear - if both dimmer and brightness are enabled. But whe only one - it did not (may be i missed some conditions).

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue.  
The issue happened to me too sometimes, but i never had the time (aka: motivation) to check it out.  
I'll surely do it this time :)  
I'm pretty sure it has something to do with a rework that went into clightd 2.0, in Clightd/src/backlight.c (https://github.com/FedeDP/Clightd/blob/master/src/backlight.c#L199).

**Comment by FedeDP** [comment]
@nick87720z  Can you test with backlight smooth transitioning off?

**Comment by FedeDP** [comment]
As i'm no more experiencing the bug with latest master, i'll consider this issue fixed.
Please feel free to re-open the issue in case you are still affected.

Moreover, i finally managed to release clight and clightd 2.2 :)
