### ISSUE TITLE
Gamma support on wlroots

### ISSUE THREAD

**Issue by CameronNemo** [FedeDP/Clight#34]
Please implement gamma support for wlroots compositors. Further reading below.

https://github.com/swaywm/wlroots/blob/master/examples/gamma-control.c

https://github.com/swaywm/wlroots/blob/master/protocol/gamma-control.xml

**Comment by FedeDP** [comment]
Hi!
Thanks for your feedback! 
Gamma support on wayland is something i have investigated a couple of times in the past, but never actually implemented it as there wasn't a "standard" way to do that on wayland before.
I heard of wlroots and i'm open for it. 
This feature needs to be implemented in clightd though :)
But i'll track it down here.
Thank you very much for the links too!

**Comment by FedeDP** [comment]
Closing as i track it on clightd: https://github.com/FedeDP/Clightd/issues/9.
Thanks!
