### ISSUE TITLE
Wrong number of ...

### ISSUE THREAD

**Issue by a-ozkan** [FedeDP/Clight#54]
Uncomment **ac_capture_timeouts**, **batt_capture_timeouts**, **gamma_temp**  config options, clight says:
```
Wrong number of ac_capture_timeouts array elements.
Wrong number of batt_capture_timeouts array elements.
Wrong number of gamma_temp array elements.
```
Clight version: 3.1

**Comment by FedeDP** [comment]
Thanks for reporting this issue! Will look into it as soon as possible!

**Comment by FedeDP** [comment]
Fixed in latest commit!

**Comment by a-ozkan** [comment]
Thank you!

**Comment by ro6** [comment]
Just had the same error on the same Clight version and can't build `clight-git`. I'll make another issue for that.
