### ISSUE TITLE
Missing dbus dependency on wiki

### ISSUE THREAD

**Issue by lig** [FedeDP/Clight#65]
There is no mention of `dbus-devel` (or similar) package here https://github.com/FedeDP/Clight/wiki/Build

However, on Fedora 29 installing 3.1 release fails with the following message
```
CMake Error at CMakeLists.txt:76 (install):
  install FILES given no DESTINATION!
```

Installing `dbus-devel` fixes the issue.

**Comment by FedeDP** [comment]
Hi, thanks for opening this issue.
Clight does require sd-bus library, and indeed it is stated in wiki: https://github.com/FedeDP/Clight/wiki/Build (libsystemd, first dep).

**Comment by FedeDP** [comment]
Ah i see now; sorry i misread your issue. 
You are right, it is a build-dep indeed; thanks!

**Comment by lig** [comment]
@FedeDP then it could be the way Fedora 29 packages are organized. I had `systemd/sd-bus.h` installed via `systemd-devel` package. However, `dbus-1` utility is not a part of this package. You need to install `dbus-devel` in order to avoid the error mentioned.

**Comment by FedeDP** [comment]
It is fixed now; thank you very much for reporting this issue :)
https://github.com/FedeDP/Clight/wiki/Build
