### ISSUE TITLE
Support for brightness changes based off of ALS devices

### ISSUE THREAD

**Issue by scallopedllama** [FedeDP/Clight#68]
It's very cool how Clight can use a webcam to detect ambient light levels, but some devices have an IIO ambient light sensor device, like the OPT3001.

It would be cool of Clight could use one of those to get the ambient light level instead of a webcam.

**Comment by FedeDP** [comment]
Hi, thanks for the suggestion!
Clightd already supports [ALS devices](https://github.com/FedeDP/Clightd/wiki/Sensors). 
Thus clight supports it too.
Is it not working for you?

**Comment by scallopedllama** [comment]
Oh Neat! Thanks I just didn't notice that.
