### ISSUE TITLE
LKeeping an eye on the action

### ISSUE THREAD

**Issue by brianread108** [FedeDP/Clight#69]
How can I check what clight is doing?
I can see the console output if I run it specifically in a command window, but if it is runnming in the background I can't see where it might be logging its actions..

**Comment by FedeDP** [comment]
Hi!
Clight's log is located in `$HOME/.clight.log`.  
You can even start clight in verbose mode or change verbosity at runtime (https://github.com/FedeDP/Clight/wiki/Api#bus-properties, look for _Verbose_ property).

I added information about where to look for log file to [Testing](https://github.com/FedeDP/Clight/wiki/Testing) wiki page. Previously it was only mentioned in [Getting Started](https://github.com/FedeDP/Clight/wiki/Getting-Started) wiki, inside list of features.
