### ISSUE TITLE
[Request] Separate dim state timing for entering/leaving

### ISSUE THREAD

**Issue by Alkotronikk** [FedeDP/Clight#72]
Would be possible to have separate dim timings for entering and leaving dim state? I'd love to have slow entering non-invasive dim entering state but quick leaving state.

**Comment by FedeDP** [comment]
Hi! Thanks for this suggestion!
This is a tiny but interesting feature; i'll surely implement it!

**Comment by FedeDP** [comment]
This should now be supported in master :) 
Care to test?

**Comment by Alkotronikk** [comment]
I can confirm that it works great. Thanks!

**Comment by FedeDP** [comment]
That's a QUICK response! :) Thanks!
