### ISSUE TITLE
recapture

### ISSUE THREAD

**Issue by leorr** [FedeDP/Clight#74]
Hey, i was wondering would be cool the feature to send a recapture message to a running clight process to re calibrate the backlight, is this already a feature which i missed or not?

**Comment by FedeDP** [comment]
Hi!
Yes, it obviously is already there! There is a [desktop file](https://github.com/FedeDP/Clight/blob/master/Extra/desktop/clightc.desktop) too, shipped exactly for this purpose.
Or you can use Clight bus api (this is exactly what desktop file does): https://github.com/FedeDP/Clight/wiki/Api#orgclightclight.

Ie: `busctl --user call org.clight.clight /org/clight/clight org.clight.clight Calibrate`
