### ISSUE TITLE
Clight is failing to start on Ubuntu 16.04

### ISSUE THREAD

**Issue by alekcacko** [FedeDP/Clight#8]
Steps to reproduce:

1. Enable clightd systemctl service:
    $ sudo systemctl enable clightd.service
    $ sudo systemctl start clightd.service

2. Try to start clight from command line:
    $ clight
    Config file /home/mate/.config/clight.conf not found.
    Bus support started.
    Message recipient disconnected from message bus without   replying
    Bus destroyed.

3. Or try to start with systemctl
    $ systemctl --user start clight.service

So clightd service just doesn't want to start

Logs:

Systemctl: https://pastebin.com/X5dKjzSS
journalctl: https://pastebin.com/5Y6vHt1p

**Comment by FedeDP** [comment]
Can you paste me the output of  
`coredumpctl  dump` 
(if it fails to find clightd dump, please run it as root)

**Comment by alekcacko** [comment]
Here is the log from coredumpctl dump I managed to obtain:
https://pastebin.com/rFYN87wh

**Comment by FedeDP** [comment]
Wow it seems you haven't got a maxbrightness attribute for your backlight interface...i didn't think this could happen.
Can you paste me output of:
`ls /sys/class/backlight/* | grep max`
Thank you!

**Comment by alekcacko** [comment]
The output of the command:

     $ ls /sys/class/backlight/* | grep max
    ls: cannot access '/sys/class/backlight/*': No such file or directory

**Comment by FedeDP** [comment]
Uhm, what about:
`ls /sys/class/backlight/*`?

**Comment by alekcacko** [comment]
EDIT:

All I forgot to tell you is that I am trying to run this on a PC, not laptop.

And as far as I know, we can't change brigthness on PC monitor right?

**Comment by FedeDP** [comment]
It can probably be issue's cause.
Btw i don't know if you can change brightness on a pc...do you have any interface in /sys/class/backlight/?

**Comment by alekcacko** [comment]
Well, no. the backlight folder is empy.

**Comment by FedeDP** [comment]
Then you're out of luck :(

**Comment by alekcacko** [comment]
Oh it's okay, since the monitor I am using doesn't have hardware brigthness.
The issue can be closed.

Thank you for your great support though.

**Comment by FedeDP** [comment]
You're welcome! I hope you can try it out succesfully in some laptop :)
