### ISSUE TITLE
Question: how to modify brightness ratios

### ISSUE THREAD

**Issue by demoy** [FedeDP/Clight#85]
Hello. How do I modify backlight to ambient light ratio? I want to make the backlight  alot closer to ambient, especially in low lighting places. I see AcCurvePoints in the API is this it, how do I use it?

**Comment by FedeDP** [comment]
Hi!
You should take a look at ac_backlight_regression_points and and batt_backlight_regression_points in /etc/default/clight.conf file: https://github.com/FedeDP/Clight/blob/master/Extra/clight.conf#L124 .

**Comment by demoy** [comment]
Thanks I'll have a look at it.
