### ISSUE TITLE
Enable ambient gamma not toggled to 'TRUE'

### ISSUE THREAD

**Issue by ModDM** [FedeDP/Clight#88]
Just 2 questions to get a clearer view:

- Is temperature the same as brightness level?
- Is gamma something different than brightness?

Is red blue green independent settings also included in one of the settings (brightness or gamma)?

_Note: I work with gamma settings every day `(xgamma)`, but that kind of gamma (with values of 1 and lower for dark red / blue / green and 1 and higher for light red / blue / green) seems something different, because I read in your documentation about gamma values of 6000, which sound more like Kelvin values?_

Now my issue:

In /etc/default/clight.conf I uncommented `ambient_gamma = true; `(I set it to true)

Now when I go to $HOME/.clight.log I read `* Ambient gamma:                Disabled`.

Am I missing something? I thought it should be Enabled now.

_Note: Brightness is adjusted automatically every 10 minutes by webcam, but as said above, I suppose this is something different (this might be ambient brightness, which is different than ambient gamma?)._

**Comment by FedeDP** [comment]
> In /etc/default/clight.conf I uncommented ambient_gamma = true; (I set it to true)
Now when I go to $HOME/.clight.log I read * Ambient gamma: Disabled.

You need to restart clight to see it updated.
Ambient gamma, as explained in conf file, means that screen temperature will change together with screen backlight; this means that in a darker room you will have a lower screen backlight AND a "more red" screen temperature.

> because I read in your documentation about gamma values of 6000, which sound more like Kelvin values?

Yup, it is screen temperature.
