### ISSUE TITLE
[BUG] Move logging to $XDG_DATA_HOME

### ISSUE THREAD

**Issue by ainola** [FedeDP/Clight#99]
clight outputs logs to ~/.clight.log. To avoid filesystem clutter, it might be worthwhile to put it in `XDG_DATA_HOME` (which defaults to ~/.local/share/ if not set). Or possibly even systemd's user journal.

**Comment by FedeDP** [comment]
You are right! This is very easy! Moreover, i already use XDG_DATA_HOME and XDG_CONFIG_HOME for custom modules and per-user conf file. 
I don't know why i overlooked that!

**Comment by FedeDP** [comment]
Clight log file is now inside XDG_DATA_HOME/clight/ folder.
